name: "Hello world workflow"

#controls when action will run. Triggers the workflow on push done to master or production branch
on:
  push:
    branches:
      - '*'
      - production
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "Hello world"
      - name: "Print current date"
        run: date
      - name: "Print any branch"
        run:  echo "any branch executed"

